runtime: nodejs10

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /LucidNodes/.*
  secure: always
  redirect_http_response_code: 301
  script: auto
  
network:
  forwarded_ports:
    - 8080/tcp
	
