runtime: nodejs10

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  static_files: LucidNodes/index.html
  upload: LucidNodes/index.html
  
- url: /
  static_dir: LucidNodes
  
# - url: /(.*)\.html
#  script: index.js
#  secure: always
#  redirect_http_response_code: 301
#  script: auto
