runtime: nodejs10

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
 
- url: /assets
  static_dir: assets
  
- url: /css
  static_dir: css
  
- url: /userHelpDocs
  static_dir: userHelpDocs
  
- url: /userImages
  static_dir: userImages
  
- url: /userfiles
  static_dir: userfiles
  
- url: /themes
  static_dir: themes
  
- url: /lucidNodes-addons
  static_dir: lucidNodes-addons
  
- url: /contextMenu
  static_dir: contextMenu

- url: /lucidNodes-modules
  static_dir: lucidNodes-modules
  
- url: /js
  static_dir: js
  
- url: /libs
  static_dir: libs
  
- url: /
  static_dir: /

- url: /css/style\.css
  static_files: /css/style.css
  upload: /css/style.css
  
- url: /(.*)\.js
  static_files: /(.*).js
  upload: /(.*).js
 
- url: /index\.html 
  static_files: index.html
  upload: index.html 

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
