runtime: nodejs10

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:

- url: /index\.html 
  static_files: index.html
  upload: index.html
 
- url: /assets
  static_dir: assets
  
- url: /css
  static_dir: css

- url: /lucidNodes-modules
  static_dir: lucidNodes-modules
  
- url: /js
  static_dir: js
  
- url: /libs
  static_dir: libs

- url: /css/style\.css
  static_files: /css/style.css
  upload: /css/style.css
 
- url: /(.*)\.js 
  static_files: (.*).js
  upload: (.*).js
  
#- url: /LucidNodes
#  static_files: index.html
#  upload: index.html
#  
#- url: /
#  static_dir: LucidNodes
  
# - url: /(.*)\.html
#  script: index.js
#  secure: always
#  redirect_http_response_code: 301
#  script: auto