runtime: nodejs10

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /index\.html 
  static_files: index.html
  upload: index.html
 
- url: /assets
  static_dir: assets
  
- url: /assets/css
  static_dir: assets/css

- url: /assets/css/style\.css
  static_files: /assets/css/style.css
  upload: /assets/css/style.css
 
- url: /(.*)\.js 
  static_files: (.*).js
  upload: (.*).js
  
#- url: /LucidNodes
#  static_files: index.html
#  upload: index.html
#  
#- url: /
#  static_dir: LucidNodes
  
# - url: /(.*)\.html
#  script: index.js
#  secure: always
#  redirect_http_response_code: 301
#  script: auto