runtime: nodejs10
instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
 
- url: /
  static_dir: assets
  
- url: /
  static_dir: css
  
- url: /
  static_dir: userHelpDocs
  
- url: /
  static_dir: userImages
  
- url: /
  static_dir: userfiles
  
- url: /
  static_dir: themes
  
- url: /
  static_dir: lucidNodes-addons
  
- url: /
  static_dir: contextMenu

- url: /
  static_dir: lucidNodes-modules
  
- url: /
  static_dir: js
  
- url: /
  static_dir: libs
  
- url: /
  static_dir: /

- url: /css/style\.css
  static_files: /css/style.css
  upload: /css/style.css
 
- url: /index\.html 
  static_files: index.html
  upload: index.html 

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
